name: Test Push

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create file
        run: echo "Test push $(date)" > test.txt

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GH_PAT }}
          message: "Test push"
          add: "test.txt"
          branch: main
          push: true
